language: c
os:
  - linux
dist: bionic
addons:
  apt:
    packages:
      - astyle
      - aspcud
      - libgnomecanvas2-dev
      - libgtk2.0-dev
      - libgtksourceview2.0-dev
      - cvc4
      - cvc3
      - z3

cache:
  directories:
    - $HOME/bin
    - $HOME/.opam

env:
  global:
    - WP_TIMEOUT=1
    - WP_PROCESSES=3

before_install:
  - sudo apt update -qq
  - which opam || (
      wget --no-clobber https://github.com/ocaml/opam/releases/download/2.0.5/opam-2.0.5-x86_64-linux -O $HOME/bin/opam &&
      chmod +x $HOME/bin/opam
    )
  - opam init --auto-setup --disable-sandboxing --comp=4.06.0

install:
  - opam update
  - opam install --yes depext
  - opam depext  --yes frama-c
  - opam install --yes alt-ergo why3 why3-coq coq
  - opam pin add --yes frama-c 20.0
  - eval $(opam config env); why3 config --detect

script:
   - make -C StandardAlgorithms clean
   - make -C StandardAlgorithms report-clean
   - make -C StandardAlgorithms test
   - eval $(opam config env); make -C StandardAlgorithms report
   - git diff
