language: c
os:
  - linux
dist: eoan
addons:
  apt:
    packages:
      - astyle
      - aspcud
      - libgnomecanvas2-dev
      - libgtk2.0-dev
      - libgtksourceview2.0-dev
      - cvc4
      - cvc3
      - z3

cache:
  directories:
    - $HOME/bin
    - $HOME/.opam

env:
  global:
    - WP_TIMEOUT=6
    - WP_PROCESSES=2

before_install:
  - sudo apt update -qq
  - which opam || (
      wget --no-clobber https://github.com/ocaml/opam/releases/download/2.0.4/opam-2.0.4-x86_64-linux -O $HOME/bin/opam &&
      chmod +x $HOME/bin/opam
    )
  - opam init --auto-setup --disable-sandboxing 
  - opam install --yes depext

install:
  - which eprover || ( wget https://github.com/eprover/eprover/archive/E-2.3.tar.gz && tar xf E-2.3.tar.gz && cd eprover-E-2.3 && ./configure --prefix=$HOME && make -j2 && sudo make install )
  - opam update
  - opam upgrade --yes
  - opam depext --yes --noninteractive --install frama-c alt-ergo why3
  - eval $(opam config env); why3 config --detect

script:
   - make -C StandardAlgorithms clean
   - make -C StandardAlgorithms report-clean
   - make -C StandardAlgorithms test
   - eval $(opam config env); make -C StandardAlgorithms report
   - git diff
